Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Exclude:
    - lib/confluence/api.rb
    - lib/dbdoc/cli.rb

Metrics/AbcSize:
  Exclude:
    - lib/dbdoc/cli.rb

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Security/YAMLLoad:
  Enabled: false
